[build]
rustc-wrapper = "sccache"
jobs = 2

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[alias]
console = [
  "run",
  "--config",
  "build.rustflags=['--cfg', 'tokio_unstable']",
  "--config",
  "build.target-dir='target/tokio-console'",
]
