[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
shared = { workspace = true }
ractor = { workspace = true }
reqwest = { workspace = true }
scraper = { workspace = true }
url = { workspace = true }
rusqlite = { workspace = true }
bloomfilter = { workspace = true }
uuid = { workspace = true }
headless_chrome = { workspace = true }
lopdf = { workspace = true }
quick-xml = { workspace = true }
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "extract_bench"
harness = false
