[package]
name = "query"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
shared = { workspace = true }
axum = { workspace = true }
reqwest = { workspace = true }
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lapin = { workspace = true }
serde_json = { workspace = true }
tower-http = { workspace = true }
reqwest-tracing = { workspace = true }
reqwest-middleware = { workspace = true }
pprof = { workspace = true, features = ["flamegraph"] }

[dev-dependencies]
criterion = { workspace = true }
mockito = "1.7.2"

[[bench]]
name = "query_logic_bench"
harness = false
